### ISSUE TITLE
Default to "all" when installing a group

### ISSUE THREAD

**Issue by Mako88** [oshazard/apacman#66] opened 2016-05-13 13:53 UTC
When a group is selected for install in pacman, the default is to install all packages. In apacman the default is just to install the first one. Can this be fixed?

**Comment by oshazard** [comment] 2016-10-05 06:59
Dupe of #51. 
Fixed in 2abca2ee77ca340bde47876e5669d44e2172fbf5

**Closed by oshazard** 2016-10-05 06:59 UTC
